language: go
install: true
sudo: false
go:
  - 1.6
  - tip
env:
  matrix:
    - GOARCH=amd64
script:
  - go test -x
  - go build -ldflags "-linkmode external -extldflags -static"
services:
  - mongodb
  - docker
matrix:
  allow_failures:
    - go: tip
