language: go
install: true
sudo: required
go:
  - 1.6
  - tip
env:
  matrix:
    - GOARCH=amd64
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
script:
  - go test -x
  - go build -ldflags "-linkmode external -extldflags -static"
services:
  - mongodb
  - docker
