language: go
install: true
sudo: required
go:
  - 1.6.2
  - tip
env:
  matrix:
    - GOARCH=amd64
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mongodb
script:
  - go test -x
  - go build -ldflags "-linkmode external -extldflags -static"
services:
  - docker
